# conditional CIFAR10 generation with SN and projection discriminator
batchsize: 64
disc_update: 2
epochs: 100
summary_every_n_steps: 422
save_every_n_steps: 10000
truncation: 0.5

model:
  generator:
    name: generator.u_net_generator_128
    args:
      ch: 32
      output_depth: 2


  discriminator:
    name: discriminator.snresnet_128
    args:
      ch: 64

dataset:
  name: cats_vs_dogs
  img_size: 128

optimizer:
  generator:
    learning_rate: 0.0001
    beta_1: 0.0
    beta_2: 0.9

  discriminator:
    learning_rate: 0.0004
    beta_1: 0.0
    beta_2: 0.9