# conditional CIFAR10 generation with SN and projection discriminator
batchsize: 32
disc_update: 2
epochs: 4
summary_every_n_steps: 300
save_every_n_steps: 10000
truncation: 0.5

model:
  generator:
    name: generator.resnet_generator
    args:
      ch: 32
      output_depth: 2


  discriminator:
    name: discriminator.patch_resnet_discriminator
    args:
      ch: 64

dataset:
  name: cats_vs_dogs
  img_size: 256

optimizer:
  generator:
    learning_rate: 0.0001
    beta_1: 0.0
    beta_2: 0.9

  discriminator:
    learning_rate: 0.0004
    beta_1: 0.0
    beta_2: 0.9